# Generated by Django 6.0.1 on 2026-02-01 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="URLModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="短網址代碼",
                    ),
                ),
                (
                    "original_url",
                    models.URLField(max_length=2048, verbose_name="原始網址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="擁有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "短網址",
                "verbose_name_plural": "短網址",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="點擊時間"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 位址")),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="瀏覽器"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="作業系統"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="裝置類型"
                    ),
                ),
                (
                    "referer",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="來源網站"
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="shortener.urlmodel",
                        verbose_name="短網址",
                    ),
                ),
            ],
            options={
                "verbose_name": "點擊記錄",
                "verbose_name_plural": "點擊記錄",
                "ordering": ["-clicked_at"],
            },
        ),
    ]
