# Generated by Django 6.0.1 on 2026-02-09 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="urlmodel",
            constraint=models.UniqueConstraint(
                fields=("user", "original_url"), name="unique_user_url"
            ),
        ),
    ]
