# Generated by Django 6.0.1 on 2026-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_add_unique_constraint_user_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clicklog",
            options={
                "ordering": ["-clicked_at"],
                "verbose_name": "Click Log",
                "verbose_name_plural": "Click Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="urlmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
            },
        ),
        migrations.AddField(
            model_name="urlmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
