# Generated by Django 6.0.1 on 2026-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_clicklog_options_alter_urlmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlmodel",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="到期時間"),
        ),
    ]
